### ISSUE TITLE
Requests other then GET are not properly send

### ISSUE THREAD

**Issue by CptArn** [bjowes/cypress-ntlm-auth#11]
It seems that any request other than GET (POST, PUT, DELETE) is not properly send through the proxy. I get a request verb is invalid and a 400 error code. I had a similar approach with a proxy script with all verbs configured and this is a better solution, but i would need support for all the other requests to use this library. 

I can try to have a look in a dead moment, but for now, not much time to dig into this.

**Comment by bjowes** [comment]
Thanks for reporting, I will investigate.

**Comment by CptArn** [comment]
@bjowes After a fast look, it seems that the body part isn't set in the proxy logic in src/proxy/server.js. Not sure if there it should be available but the hasbody is true, but nowhere to be found in the requests.

**Comment by bjowes** [comment]
@CptArn It is intentional that the body is not sent in the request for the first part of the NTLM handshake. What I found yesterday was that too many headers are sent with that request, which may confuse the host (headers indicate a body is included but it isn't). The result is that the host closes the socket before the real incoming request with body is passed the host.

I will try removing the copying of headers from the real incoming request to the NTLM handshake request and see if that resolves the issue. So, in src/proxy/server.js, replacing
```javascript
let requestOptions = {
      method: ctx.proxyToServerRequestOptions.method,
      path: ctx.proxyToServerRequestOptions.path,
      host: ctx.proxyToServerRequestOptions.host,
      port: ctx.proxyToServerRequestOptions.port,
      headers: JSON.parse(
       JSON.stringify(ctx.proxyToServerRequestOptions.headers)), // Deep copy
      agent: ctx.proxyToServerRequestOptions.agent,
    };
```
with
```javascript
let requestOptions = {
      method: ctx.proxyToServerRequestOptions.method,
      path: ctx.proxyToServerRequestOptions.path,
      host: ctx.proxyToServerRequestOptions.host,
      port: ctx.proxyToServerRequestOptions.port,
      headers: {},
      agent: ctx.proxyToServerRequestOptions.agent,
    };
```
I'll test it tonight.

**Comment by CptArn** [comment]
@bjowes Saving you the time tonight, this fix works for me 👍 Could you notify me when there is a new release?

Thanks for the quick help!

**Comment by bjowes** [comment]
@CptArn cool! Likely it will be released tonight (within 12 hours from now).

**Comment by bjowes** [comment]
@CptArn : Release 0.6.0 available. Issue resolved.
