### ISSUE TITLE
No Log Results

### ISSUE THREAD

**Issue by smit9234** [bjowes/cypress-ntlm-auth#12]
Hi,  I am trying to get this to work, but I am not getting any console log results that tell me the test is working or not when I use the cy.ntlm command.  

Here is the cypress test output:
![image](https://user-images.githubusercontent.com/7388782/51346182-daf9fc00-1a51-11e9-8d53-9654b83ce2fb.png)

And then in the browser console all I see is this:
![image](https://user-images.githubusercontent.com/7388782/51346244-00870580-1a52-11e9-871e-3c4058df54b3.png)

Is there a way to see if the NTLM authentication actually was submitted?

I was looking at the index.js file in src\commands, and it seems like there should be some console output for the results (line 52-62), where does the log.ConsoleProprs output to?  

I am relatively new to the Cypress framework, so maybe I am missing something in my configuration.

**Comment by bjowes** [comment]
Hi @smit9234,
Whether NTLM authentication is used or not when calling cy.visit or cy.request is not logged in Cypress, since the authentication is provided transparently - Cypress won't know about it. But normally it shouldn't be required. If you really need logging, activate debug logging for the ntlm-proxy (see the README for examples)

If the host you are testing requires NTLM authentication, it will fail (return 401) if the authentication isn't active (not configured for the host) or if the credentials are invalid. Otherwise it should always return some other status code than 401, which implies that the NTLM authentication was successfully applied. 
Hence, looking at your screenshot, it appears to be working since your are receiving status code 200. To verify this, just remove the cy.ntlm command (put in a cy.ntlmReset() call to be sure) and check if your test results in 401 instead. If not, your host does not require NTLM.

The log.consoleProps defines what Cypress will log in the browser console when you execute the cy.ntlm command. This includes all the options sent to the command except the password. This is only logged during cy.ntlm, not on any other commands that utilizes the NTLM authentication.

One thing in your screenshot catches my eye - on your VISIT step, it seems that the host returns a 301 status code, meaning that you are redirected. The cy.ntlm command must be applied for all involved hosts - if your browser is redirected, it will send requests that follow to another host. If this host also requires NTLM authentication, that host must be configured with cy.ntlm too. This also applies when using the same host with http and https (or additional ports) - every protocol/port/host combination is handled as a unique host and must be configured with cy.ntlm if they require NTLM authentication.

Please let me know if this helped you out.

**Comment by smit9234** [comment]
Thanks for the response, @bjowes 

I was able to get logging on the ntlm-proxy to work, but I still am having issues with authenticating to my site.

For context, here is my test code:
![image](https://user-images.githubusercontent.com/7388782/51400830-37b2f080-1afe-11e9-8a0a-be14180b9fdd.png)

Here is the log output from the ntlm-proxy:
![image](https://user-images.githubusercontent.com/7388782/51401058-bdcf3700-1afe-11e9-8288-753deca3a554.png)


When I run the test, the browser console is showing a 401 unauthorized:
![image](https://user-images.githubusercontent.com/7388782/51400637-c3784d00-1afd-11e9-8004-2bfa89227f21.png)


To validate that NTLM is configured for the url, I used Postman with the same credentials and it returns a 200 response.

The ntlm-proxy log is showing some interesting errors, I am not sure what those mean.

**Comment by bjowes** [comment]
Thanks @smit9234 , that makes it much easier to track down. Just some quick feedback now, I have more time to look at this later.

1. Upgrade to latest version - it works better with other requests than GET and the errors you see in the debug log are clarified (those are actually just Chrome checking the network environment - not actual errors)

2. When you see "Tunnel to labassisttest...", it means that the proxy is tunnelling all traffic to that host without NTLM authentication. The reason is that you called cy.ntlm with both host (https://labassisttest.xyz.xyz) and path (/activities/api/users/current). Normally you should call cy.ntlm with only the host. Then it will match the host and apply NTLM instead of establishing a tunnel.

However, your use case seems a bit different from what I had anticipated. It seems that NTLM is only required for that specific path - otherwise you should see 401 on all the requests. Is this the case? Then the proxy needs to be adapted, so that it doesn't establish the tunnel if only the host part matches a configured NTLM host. I will take a look at this.

You can test that the NTLM part is working for you if you insert a cy.request call right below the cy.ntlm call, and address the host and path. Then it should match and authenticate. But I still need to look into host only matching to get your actual test working.

**Comment by smit9234** [comment]
@bjowes 

Thanks again, I was able to get my test to work, I found out that we did not have our web server configured for NTLM auth at the domain level (go figure).  I was able to test one of our other sites with NTLM configured correctly, and the ntlm-proxy works like a charm.

**Comment by bjowes** [comment]
Great news @smit9234 !
Just to clarify, do you still need the ability to set NTLM only for a specific path of a site? Just want to know if I should prioritise that or not.

**Comment by smit9234** [comment]
@bjowes 
I will let you know.  Server guys are trying to setup the correct configuration, the issue is we have authentication on the redirect but not at the host level.

**Comment by bjowes** [comment]
@smit9234 I am closing this now. 

The latest version gives decent error messages directly in cypress if you try to register ntlm hosts with a path. If you find that you actually need this feature, please open a new issue as a feature request.

**Comment by smit9234** [comment]
@bjowes 
I did see the new error log output which is awesome.  BTW I was able to get this plugin fully implemented in our CI/CD pipeline, this is an awesome plugin, thanks for developing it.
