### ISSUE TITLE
Unable to load local resources (css, js, etc.)

### ISSUE THREAD

**Issue by andrewleith** [bjowes/cypress-ntlm-auth#18]
Thank you so much for writing this plugin!

When I try to use it, the initial request to my site is successful (200 OK), but all subsequent requests are getting error 500.  Is there something I might be doing wrong?  I am not doing anything special besides what is in the documentation for your plugin.

Thanks,
Andrew

**Comment by bjowes** [comment]
Hi @andrewleith ,

Thanks for the praise :) 
Let's get it working for you!

I would need some debug logs to get a better grip on this. Could you please provide them? You can anonymise hosts if needed. Use the examples from the README to activate debug logging on the ntlm-proxy.

Also: 
* Given that you reported this recently, I assume you are using the latest version (0.8.1)? 
* Are you behind a corporate proxy?
* Please clarify the local resources - I assume these items are loaded on the web page of the initial request (script tags and img tags)? 
* Are the local resources on the same host as the site - or is something on a CDN (such as jquery or bootstrap)?

**Comment by andrewleith** [comment]
Hi @bjowes,

Thanks for your help!

Answers to your questions:
- Yes, 0.8.1
- Behind proxy, but not trying to access anything through the proxy (everything is local)
- CSS, JS and SVG are failing with error 500
- all resources are on the same URL as the site (http://localhost:17145)

Here is the log it generated.  Nothing stands out to me there
[access.log](https://github.com/bjowes/cypress-ntlm-auth/files/2815365/access.log)

Chrome looks like this:
![image](https://user-images.githubusercontent.com/823749/52025260-17aa0680-24da-11e9-8f77-e1f960e393b9.png)

---

Side note: took me a little bit to get logging going, is this right?

In package.json, replaced:
`"ntlm-proxy": "start /min \"ntlm-proxy\" cmd /c node_modules\\.bin\\ntlm-proxy",`
with
`"ntlm-proxy": "set DEBUG=cypress:plugin:ntlm-auth && start /min \"ntlm-proxy\" cmd /c node_modules\\.bin\\ntlm-proxy",`

**Comment by bjowes** [comment]
Thanks @andrewleith . 
Yes, you have set up the debug logging correctly. I cannot see anything odd there either. Could you also provide the access/error logs from your web server? Since from the logs I see that the ntlm-proxy is doing its magic and handling authentication on all the requests, we may get more info from the web server. What server is it?

**Comment by andrewleith** [comment]
Its running in IIS express while in development.

Here is the access log from it:
[iis.express.access.log](https://github.com/bjowes/cypress-ntlm-auth/files/2817360/iis.express.access.log)

Oddly, they are all saying 200 OK in there, despite the fact that chrome inside of cypress says they are all 500 errors...

**Comment by andrewleith** [comment]
Ok so I just tried running this on IIS and everything works fine.  Any ideas why that might be? If not, I'll see if the team minds switching to full IIS for development... :)

**Comment by andrewleith** [comment]
Anyway, looks like this problem has nothing to do with your plugin so I'm closing it.  Thanks again for your help.

**Comment by andrewleith** [comment]
Thanks again.  I'll give this a shot and let you know if it fixes the issue.

**Comment by andrewleith** [comment]
Just to let you know, I tried changing the `applicationhost.config` file in my project's `.vs` folder, as well as changing the global `applicationhost.config` file, but neither fixed the problem.

**Comment by bjowes** [comment]
Ok, it was worth a shot.

**Comment by svopex** [comment]
Hello, I have the same problem. 
[http://www.ftp.svopex.com/temp/git/error-cypress-ntlm-auth-0001.png](url)
I solve it when i run visual studio as administrator.
But it is not good solution.
Some idea?

**Comment by bjowes** [comment]
Hi @svopex , it is not intentional that you must run Visual Studio as admin to use the plugin.

Could you clarify your setup a bit? 

1. What is started from Visual Studio - only the website you are testing, or are you also starting cypress from within Visual Studio
2. Please provide debug logs from the ntlm-proxy (see the README for setup)
3. Are you hosting on IIS Express, IIS or something else?
4. Check the access/error logs from the web server

**Comment by svopex** [comment]
1. I am started only website from VS.
2. 
```
cypress:plugin:ntlm-auth Request to http://127.0.0.1:64408/ - pass on +19s
cypress:plugin:ntlm-auth Created non-NTLM agent for target http://127.0.0.1:64408/ +2ms
cypress:plugin:ntlm-auth Received reset +3ms
cypress:plugin:ntlm-auth Removed all agents due to reset +30ms
cypress:plugin:ntlm-auth Request to http://127.0.0.1:64408/ - pass on +23ms
cypress:plugin:ntlm-auth Created non-NTLM agent for target http://127.0.0.1:64408/ +11ms
cypress:plugin:ntlm-auth Received valid config update +13ms
cypress:plugin:ntlm-auth Request to http://localhost:61719/ in registered NTLM Hosts +38ms
cypress:plugin:ntlm-auth Created NTLM ready agent for client 127.0.0.1:64481 to target http://localhost:61719/ +4ms
cypress:plugin:ntlm-auth Sending  NTLM message type 1 +3ms
cypress:plugin:ntlm-auth received NTLM message type 2 +2ms
cypress:plugin:ntlm-auth Sending NTLM message type 3 with initial client request +6ms
cypress:plugin:ntlm-auth NTLM authentication successful for host http://localhost:61719/ +8ms
cypress:plugin:ntlm-auth Removed agent for 127.0.0.1:64481 due to socket.close +1ms

```
3.
![settings](https://user-images.githubusercontent.com/16083944/53080349-bf728d00-34f8-11e9-9c5f-647762129d1f.png)

4.
```
#Software: Microsoft Internet Information Services 10.0
#Version: 1.0
#Date: 2019-02-20 09:20:02
#Fields: date time s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(User-Agent) cs(Referer) sc-status sc-substatus sc-win32-status time-taken
2019-02-20 09:20:02 ::1 GET / - 61719 - ::1 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/72.0.3626.109+Safari/537.36 - 401 2 5 1231
2019-02-20 09:20:02 ::1 GET / - 61719 HAVIT\svoboda ::1 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/72.0.3626.109+Safari/537.36 - 200 0 0 206
2019-02-20 09:20:24 127.0.0.1 GET /version.txt - 61719 HAVIT\svoboda 127.0.0.1 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/72.0.3626.109+Safari/537.36 - 500 0 1346 38
```

**Comment by svopex** [comment]
Here are my sources:
[http://www.ftp.svopex.com/temp/git/cypress-ntlm-test.zip](url)
Only need run npm install and change paths in ntlm-cypress.cmd and ntlm-proxy.cmd.

**Comment by bjowes** [comment]
Thanks @svopex , I have successfully tested your code. Since this seems to be a pure IIS Express issue I opened a separate issue (#21) for documenting this properly. We can continue the discussion here and I will add any tips/tricks to resolve it in the other issue.

When I did some manual tests, I found that (not running Visual Studio as Admin):
Logging in with the same user account as I am logged into the computer:
* http://localhost:61719 works fine
* http://localhost:61719/Default.aspx works fine
* http://localhost:61719/Version.txt works fine

Logging in with another user account:
* http://localhost:61719 returns 500
* http://localhost:61719/Default.aspx works fine and shows the correct user
* http://localhost:61719/Version.txt returns 500

I believe that when IIS Express is trying to access a static file or directory it performs impersonation for the logged in user. This fails since IIS Express cannot do impersonation without administrative privileges.

Since the result is the same when accessing the site manually or through the plugin, it is clear this is not related to the plugin itself. But if you find a way to work around this I am very interested to hear it since I am sure this will happen to many users.

**Comment by Yamo93** [comment]
I'm experiencing the same problem. It prevents us from integrating Cypress into our project.

**Comment by bjowes** [comment]
Hi @Yamo93 - Do you mean that you have issues with local resources when running the site locally using IIS Express? As mentioned in my comment, this is an IIS Express issue which cannot be solved by the plugin. If you use the full IIS on the local machine it should work.

**Comment by Yamo93** [comment]
Thanks for the reply @bjowes !
