### ISSUE TITLE
cypress.ntlm - cy.visit() - Not secure

### ISSUE THREAD

**Issue by Rashminair88** [bjowes/cypress-ntlm-auth#196]
Hello,

I am trying to access an intranet application through cypress.ntlm. I am able to log in but the page rendering is weird. Manually I am able to access the page. 
On the header it shows "Not secure" while running the automation.

Thanks,

**Comment by bjowes** [comment]
Hi @Rashminair88 

This behavior is built into cypress itself. To perform some of its features, cypress must decrypt all HTTPS traffic internally. Then it serves the site to the browser with a self generated certificate. With electron browser, you won't see this, but with Chrome a warning will be displayed that the connection is unsecure. If you drill into that message, you can see that the certificate could not be verified. And if you look into the certificate details, you will see it was issued by CypressProxyCA.

You can try writing a test case agains https://google.com for instance. Even without the plugin you will see the same warning in Chrome due to the HTTPS connection.

You mention that the rendering is weird - is there anything else that is weird except for the "Not secure" message?

**Comment by bjowes** [comment]
The most likely reason for this is that some resources for the page (CSS etc) cannot be loaded. This could be because they are stored on another site that also requires NTLM authentication. Open the dev tools and run the test - you should see some failed requests for CSS and potentially more. If the status code is 401 my theory is correct. Find out which hosts are serving those resources and add them to the cy.ntlm (or cy.ntlmSso) call.

**Comment by Rashminair88** [comment]
Hello,

Yes I am seeing 401 unauthorized in the console like below.
https://<url>/<app>/styles/navigation.css?t=1645357018

I tried using 
cy.ntlm("https://<url>", 'uname', 'password');

Still getting the same error
How will I find the hosts where the CSS is stored?

Thanks!

**Comment by bjowes** [comment]
That URL looks strange! Anyway, setting cy.ntlm("https://" won't work, it must be a hostname without protocol. If you click in the CSS request in dev tools, what does the "Request URL" say in the details view? 

Something to test: cy.ntlm(["*"], 'uname', 'password'), this will attempt NTLM login on any request that requires it. If that works, it means cypress + the plugin are ok, you just need to figure out the proper hostname. It is possible to use this "wildcard" config, but it is discouraged since you shouldn't login to random places - especially with NTLM. The idea of the wildcard config is more for cases like *.my.intranet, so you don't need to add a long list of hosts.

**Comment by Rashminair88** [comment]
Hello,

This is the screenshot of the runner
![image](https://user-images.githubusercontent.com/96204241/155006569-e0fca31b-e75a-4c03-80c8-acfa14b89e3a.png)

Thanks!
Rashmi

**Comment by Rashminair88** [comment]
Hello,

Please find the attached screenshot
![image](https://user-images.githubusercontent.com/96204241/155398277-2f38bfe3-8cb2-4725-a539-294d6f6d5559.png)

Thanks!
Rashmi

**Comment by bjowes** [comment]
Sorry, but I can't get the info I need from that screenshot. See the example below, where the details of a request are shown, including the full URL.

<img width="1678" alt="Screenshot 2022-02-24 at 20 36 09" src="https://user-images.githubusercontent.com/4487404/155594828-5d5699a2-14e8-4f4c-994e-50f272f236eb.png">

Also, the CSS file you marked in your screenshot is a cypress CSS file. You need to activate developer tools and then rerun the test to see the requests performed to your site, and click the CSS loaded there.

As for your collegues issue, I would guess this is a certificate validation issue, since your site uses https. A bit odd that you aren't getting the same, but maybe your setup is slightly different. See the section in the readme about it https://github.com/bjowes/cypress-ntlm-auth#httpsssltls-issues

**Comment by Rashminair88** [comment]
Hello, 

I am not sure if this is helpful. But here is the screenshot
![image](https://user-images.githubusercontent.com/96204241/155806551-271050ed-c08a-479a-8606-16d5c8763d5a.png)

![image](https://user-images.githubusercontent.com/96204241/155806615-f7c40d22-17ac-4a03-a994-56337451c426.png)
Thanks,
Rashmi

**Comment by bjowes** [comment]
Bingo! 
If you look at the domain names of those two requests, you will see that they are slightly different.
The first image shows a request to `rhbeta.rockfin.com`
The second image shows a request to `rhbeta.rktfoc.com`
Only the second of these two domains are registered in the cy.ntlm call, and that is the only successful one. If you change your cy.ntlm call to: `cy.ntlm(['rhbeta.rockfin.com', 'rhbeta.rktfoc.com'], username, password)` you should get through. 

Hopefully that should be enought, but there may be additional resources loaded from other domains requiring NTLM authentication, so you may need to add additional domains to the cy.ntlm call. Just inspect the traffic and check the domains of all requests that are returning 401.
