### ISSUE TITLE
Connexion throught proxy with NTLM authentification 

### ISSUE THREAD

**Issue by PereiraMV** [bjowes/cypress-ntlm-auth#247]
Hello, 
I have to connect to a corporate proxy that requires NTLMv2 authentification. Right now it works throught CNTLM but i dont have access to it on the CI/CD pipelines. If I understood correctly  cypress-ntlm-auth doesn't support connexion to proxy with authentification. Is it a feature that you plan to implement or do you know any way to go around ?

**Comment by bjowes** [comment]
Hi @PereiraMV 
At the moment there are no plans to add support for authenticated proxies. Unless you can get around it by using only local resources (serving fonts, js libs and so on from you site instead of external CDNs - this presumes that you can reach your test site without passing through the proxy), you need something like CNTLM to get through.

**Comment by PereiraMV** [comment]
Ok, thank you for the fast answer
