### ISSUE TITLE
Reading Windows Certs

### ISSUE THREAD

**Issue by btsimonh** [bjowes/cypress-ntlm-auth#252]
a quick note to highlight a repo I created some years back to solve the certificates issues in Nodejs:

https://github.com/btsimonh/node-windows-root-certs

This enables the root certs installed on Windows to be read and added to TLS in NodeJS, hence avoiding letting Node accept insecure certs globally.

I have not tested it above Node 12...  
However, I see you are adept at node native modules.  node-windows-root-certs uses FFI to access windows APIs, but it could be the inspiration for an update to node-win-sso or a new native module based cert updater?

br,
Simon

**Comment by bjowes** [comment]
Hi Simon,
I did some investigation into getting the certs from windows certs store
some time ago, maybe your repo was one of the sources I found.

The main reasons I haven’t moved forward on this are
* cypress itself does not perform cert validation (at least it didn’t last
I looked), so adding this to the plugin adds complexity for cypress users.
That’s why I made the cert validation optional.
* even if the plugin could access the windows cert store, npm still does
not. This means that users behind corporate proxies cannot even install
cypress and the plugin, unless they disable cert checking or setup the node
environment variable to point out a cert.

It would still be an improvement to access the windows certs store, but I
think the value is a bit limited due to the above.

fre 29 mars 2024 kl. 09:57 skrev btsimonh ***@***.***>:
