### ISSUE TITLE
Executing cypress using cli

### ISSUE THREAD

**Issue by krishvv** [bjowes/cypress-ntlm-auth#29]
Hi ,

I have followed the steps and was able to successfully use this plugin . Thanks .
How do i execute this using cli? This is needed in our cases for end to end execution

Regards,
Krish

**Comment by krishvv** [comment]
Hi . I figured out how to do this :)
1.npm run ntlm-proxy 
2.node_modules\.bin\cypress-ntlm run --browser chrome --spec <spec.js>

**Comment by bjowes** [comment]
Hi @krishvv , I'm glad you figured it out. This is pretty much identical to what I recommended in the README for package.json scripts:
```json
"cypress-ntlm": "npm run ntlm-proxy && cypress-ntlm open && ntlm-proxy-exit"
```
Two notes:
1. With your two steps, you aren't closing the ntlm-proxy after test execution. Not a big issue since the next time you start the ntlm-proxy it will terminate the old one, but I just think it is more clean to close it afterwards. The command ntlm-proxy-exit is there for this purpose
2. For automated CI use, I would recommend running in headless mode. Currently only electron is supported by Cypress for this, but [work is ongoing to support Chrome in headless mode](https://github.com/cypress-io/cypress/issues/832)
