### ISSUE TITLE
 throw new Error('ntlm-proxy must be started before this command')

### ISSUE THREAD

**Issue by vKarter** [bjowes/cypress-ntlm-auth#34]
![obraz](https://user-images.githubusercontent.com/1113891/57365107-be124180-7184-11e9-8d50-7c5fec3ed314.png)

>   "name": "cypresstests",
>   "version": "1.0.0",
>   "description": "",
>   "main": "index.js",
>   "scripts": {
>     "cy:open": "cypress open",
>     "ntlm-proxy": "start /min \"ntlm-proxy\" cmd /c node_modules\\.bin\\ntlm-proxy",
>     "cypress-ntlm": "npm run ntlm-proxy && cypress-ntlm open && ntlm-proxy-exit"    
>   },
>   "author": "",
>   "license": "ISC",
>   "devDependencies": {
>     "cypress": "^3.2.0",
>     "cypress-ntlm-auth": "^0.9.3"
>   }
> 

It happens when I use "npm run cypress-ntlm"

**Comment by bjowes** [comment]
Hi @vKarter , wondering if this might be a timing issue. Do you see the ntlm-proxy start (should open a minimized cmd window)? If the ntlm-proxy didn't finish its startup process before cypress-ntlm is run, then cypress-ntlm will assume that the ntlm-proxy wasn't started.
 
If it is a timing issue, you should be able to work around this by starting the ntlm-proxy separately. Open another cmd window and run `npm run ntlm-proxy`. Then in the first cmd window run `node_modules\.bin\cypress-ntlm open`.

If that works for you, I can look into modifying cypress-ntlm so that it will wait a while for the ntlm-proxy to start.

**Comment by vKarter** [comment]
As you said ntlm-proxy window is open as a minimized,  but then the process is broken with the error that I have described. When I first run ntlm-proxy and then node_modules\.bin\cypress-ntlm open it works. 
So good to wait until the ntlm-proxy start.

**Comment by bjowes** [comment]
Hi @vKarter , the 'wait for ntlm-proxy' feature was implemented in v0.9.4.
