### ISSUE TITLE
401 when cy.visit with user from different domain on versions newer than 1.0.7

### ISSUE THREAD

**Issue by Chase817** [bjowes/cypress-ntlm-auth#55]
I am trying to visit my site which is on domain A, with a user from domain B (note that there is trust established between these two domains, and authenticating manually with a browser has no issues). On versions 1.1.0 and 1.1.1 I get a 401 error "NTLM authentication failed, invalid credentials".

Downgrading to 1.0.7 will make the authentication work without any changes to my spec file, and changing my spec file to authenticate into a domain B machine will work on any version.

**Comment by bjowes** [comment]
Thanks for reporting @Chase817 !
This indicates that something is flawed after I replaced the NTLM library to a NTLMv2 compatible library. It might be linked to #53 . I think I need to inspect the source for the new library.

Just to clarify, which domain did you pass to cy.ntlm - domain A (where the site is) or domain B (where the user is)? It should be domain B, and I am guessing you used that since it works when the site is on domain B.

**Comment by Chase817** [comment]
@bjowes My spec looks like this:
`
cy.ntlm('http://machine.domainA.com', 'testUser', 'password', 'domainB')
cy.visit('http://machine.domainA.com/application/')
`

**Comment by bjowes** [comment]
I have identified the root cause for this. Apparently the new NTLM library I am using uses the wrong domain (domain of the site instead of domain of the user) when calculating the NTLMv2 hash. I will fork it and fix it within a few days.

**Comment by bjowes** [comment]
Hi @Chase817 , your scenario should work again with release 1.2.0. Please report back when you have tried it out.

**Comment by Chase817** [comment]
Hi @bjowes , I have tried out the new version and all seems to be working well now!
