### ISSUE TITLE
Error when run from a docker container: PROXY_TO_SERVER_REQUEST_ERROR on /: Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by DaveLHX** [bjowes/cypress-ntlm-auth#85]
So I'm on windows and the stuff works normally but I'm experimenting with running the tests from docker to use it in a jenkins build.  Right now I'm just trying to get it to work on my dev station.

Here is what I have.

1.  Site is running on localhost:8080 of my dev station.
2.  I start up a docker the the official cypress image + ntlm (https://github.com/DaveLHX/DOCKER/tree/master/cypress-ntlm)

Durring startup ntlm-auth hangs for 2 minutes and throws the error from the title.

One thing I had to do to get cypress to see my site was to use the host machine ip.
To debug I ran the commands manually in /bin/bash with your debug flag.
So this is what I get (I repaced the ip in this post with HOSTIP).
`  cypress:plugin:ntlm-auth Startup done! +0ms
  cypress:plugin:ntlm-auth {
  cypress:plugin:ntlm-auth   configApiUrl: 'http://127.0.0.1:45571',
  cypress:plugin:ntlm-auth   ntlmProxyUrl: 'http://127.0.0.1:34243'
  cypress:plugin:ntlm-auth } +0ms
  cypress:plugin:ntlm-auth Received alive +13s
cypress:plugin:ntlm-auth Created agent for client 127.0.0.1:43166 to target http://HOSTIP:8080/ +4s
  cypress:plugin:ntlm-auth Request to http://HOSTIP:8080/ - pass on +0ms
  cypress:plugin:ntlm-auth PROXY_TO_SERVER_REQUEST_ERROR on /: Error: connect ETIMEDOUT HOSTIP:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: 'HOSTIP',
  port: 8080
} +2m`

Any idea how I could get this to work if at all possible?

**Comment by bjowes** [comment]
I'm not very familiar with Docker but I don't see any reason why it shouldn't be possible. I know that the Docker container has its own network environment which needs to be mapped properly to reach the host machine, but I think you are already on that track.

If you run cypress without the plugin, does it work?
If so, could you check if cypress has received any other proxy configuration (possibly through enviroment variables) - you check this by opening cypress and clicking the "Settings" tab.

I saw also that instead of using your host IP you can use `host.docker.internal`, according to [stackoverflow](https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach)

**Comment by DaveLHX** [comment]
Well using host.docker.internal put me on the right track.  Got some parts to work, then reviewed all the ips I set when running things and it all worked. 

Just needed to take a step back.  thx.
